FROM cgoncas/slim-liferay-portal-image:20170905072647
MAINTAINER Ruben Pulido <ruben.pulido@liferay.com>

COPY *.?ar $LIFERAY_HOME/osgi/modules/
COPY portal-ext.properties /liferay/portal-ext.properties

USER root