/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.game.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Character service. Represents a row in the &quot;Game_Character&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.game.model.impl.CharacterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.game.model.impl.CharacterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Character
 * @see com.liferay.game.model.impl.CharacterImpl
 * @see com.liferay.game.model.impl.CharacterModelImpl
 * @generated
 */
@ProviderType
public interface CharacterModel extends BaseModel<Character>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a character model instance should use the {@link Character} interface instead.
	 */

	/**
	 * Returns the primary key of this character.
	 *
	 * @return the primary key of this character
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this character.
	 *
	 * @param primaryKey the primary key of this character
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this character.
	 *
	 * @return the uuid of this character
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this character.
	 *
	 * @param uuid the uuid of this character
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the character ID of this character.
	 *
	 * @return the character ID of this character
	 */
	public long getCharacterId();

	/**
	 * Sets the character ID of this character.
	 *
	 * @param characterId the character ID of this character
	 */
	public void setCharacterId(long characterId);

	/**
	 * Returns the group ID of this character.
	 *
	 * @return the group ID of this character
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this character.
	 *
	 * @param groupId the group ID of this character
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this character.
	 *
	 * @return the company ID of this character
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this character.
	 *
	 * @param companyId the company ID of this character
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this character.
	 *
	 * @return the user ID of this character
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this character.
	 *
	 * @param userId the user ID of this character
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this character.
	 *
	 * @return the user uuid of this character
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this character.
	 *
	 * @param userUuid the user uuid of this character
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this character.
	 *
	 * @return the user name of this character
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this character.
	 *
	 * @param userName the user name of this character
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this character.
	 *
	 * @return the create date of this character
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this character.
	 *
	 * @param createDate the create date of this character
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this character.
	 *
	 * @return the modified date of this character
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this character.
	 *
	 * @param modifiedDate the modified date of this character
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this character.
	 *
	 * @return the name of this character
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this character.
	 *
	 * @param name the name of this character
	 */
	public void setName(String name);

	/**
	 * Returns the url of this character.
	 *
	 * @return the url of this character
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this character.
	 *
	 * @param url the url of this character
	 */
	public void setUrl(String url);

	/**
	 * Returns the status of this character.
	 *
	 * @return the status of this character
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this character.
	 *
	 * @param status the status of this character
	 */
	public void setStatus(String status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Character character);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Character> toCacheModel();

	@Override
	public Character toEscapedModel();

	@Override
	public Character toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}